spring.application.name=Online-Learning-Management-System

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anhnd05122004@gmail.com
spring.mail.password=ndhn uopv kicq uttj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

spring.datasource.url=jdbc:sqlserver://DUCANH:1433;databaseName=HSF_Project;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# SePay payment configuration (copied from OLMS)
sepay.secret-key=A3W1SRGIUTZCVLIYEEH1B76YRQ5QLKVUHOSSCBLFM4KGKN04P9QYVINAFZIXJODC
sepay.bank-acc=0373953450
sepay.bank-name=MBBank
